version: '3.7'
services:
  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    ports:
      - "8081:80"

  backend:
    build: ./backend
    restart: always
    container_name: backend
    ports:
      - "3000:3000"
